[tool.pyright]
include = ["disnake_ext_components"]
typeCheckingMode = "basic"
strictParameterNoneValue = false
reportInvalidStringEscapeSequence = false
reportPropertyTypeMismatch = true
reportDuplicateImport = true
reportUntypedFunctionDecorator = true
reportUntypedClassDecorator = true
reportUntypedBaseClass = true
reportInvalidTypeVarUse = true
reportUnnecessaryCast = true
reportSelfClsParameterName = true
reportUnsupportedDunderAll = true
reportUnusedImport = true
reportUnusedVariable = true
reportUntypedNamedTuple = true
reportUnnecessaryComparison = true
# reportUnnecessaryTypeIgnoreComment = true
reportUnknownLambdaType = true

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
skip_gitignore = true

[tool.mypy]
namespace_packages = true
files = ["disnake_ext_components/*.py"]
