name: lint

on:
  push:
  pull_request:

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Load cached Poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-0

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Enable in-project venv
        run: poetry config virtualenvs.in-project true

      - name: Load cached virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: virtualenv-${{ hashFiles('./poetry.lock') }}

      - name: Install dependencies
        run: poetry install

      - name: Symlink ext-components
        continue-on-error: true
        run: poetry run dev-symlink

      - name: Run pyright
        run: poetry run pyright . --pythonversion ${{ matrix.python-version }}
